### ISSUE TITLE
您好,想问一下跟colly相比的优势

### ISSUE THREAD

**Issue by caoqianming** [lizongying/go-crawler#23]
如题

**Comment by lizongying** [comment]
colly 相对比较简单，主要实现了下载部分。  go-crawler 提供了比较完善的组件，更适合实际项目，比如调度、存储等。
colly 针对的是常规的链接->链接，相对通用。 go-crawler 可能更加适合垂直抓取，比如可以对category->list->detail 等不同情况进行定义，更加方便地进行数据传递，当然也支持常规的抓取。
colly 主要针对的是普通的请求。go-crawler 对一些请求过程中常见的问题提供了解决方案，比如通过中间件进行请求/返回进行修改，header修改，tls指纹修改等。
colly 类似python中request，功能更多一点。 go-crawler更像scrapy，自认为功能部分互有见长，由于结合了我自己的一些实际经验和见解，未来可能会超过scrapy。 
实际上，我不太想和colly比，因为用法不一样，一个适合临时抓取，一个适合工程项目。
更想和scrapy竞争一下，由于语言的本身特性，python看起来更简单，golang性能更好。
我相信在爬虫这块，后面一定会偏向于go-crawler。

**Comment by caoqianming** [comment]
感谢回复。我是一个python程序员，目前有一个给客户的交付项目是需要定期爬取若干指定网站存库后进行检索分析，需要提供管理后台。我计划的是用django加httpx完成。我试了一下你的项目，觉得挺好的，也有web端。我想可以用你这个试一试，基于你这个web端改造，或者结合django gocrawler只爬取但是定时任务是不是不好处理，另外我需要自定义存储数据表。不知你有什么好的建议



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月9日(周六) 晚上10:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lizongying/go-crawler] 您好,想问一下跟colly相比的优势 (Issue #23)




 
colly 相对比较简单，主要实现了下载部分。  go-crawler 提供了比较完善的组件，更适合实际项目，比如调度、存储等。
 colly 针对的是常规的链接-&gt;链接，相对通用。 go-crawler 可能更加适合垂直抓取，比如可以对category-&gt;list-&gt;detail 等不同情况进行定义，更加方便地进行数据传递，当然也支持常规的抓取。
 colly 主要针对的是普通的请求。go-crawler 对一些请求过程中常见的问题提供了解决方案，比如通过中间件进行请求/返回进行修改，header修改，tls指纹修改等。
 colly 类似python中request，功能更多一点。 go-crawler更像scrapy，自认为功能部分互有见长，由于结合了我自己的一些实际经验和见解，未来可能会超过scrapy。
 实际上，我不太想和colly比，因为用法不一样，一个适合临时抓取，一个适合工程项目。
 更想和scrapy竞争一下，由于语言的本身特性，python看起来更简单，golang性能更好。
 我相信在爬虫这块，后面一定会偏向于go-crawler。

**Comment by lizongying** [comment]
可以用这个。
golang比较好部署，直接可执行文件应该更适合第三方交付，可以保护你的代码。
框架本身支持定时任务及自定义存储，方便。
至于管理后台，这个主要还是针对爬虫的管理。至于数据管理考虑到数据的规模及结构千差万别，不适合做成通用的，后面可能会考虑提供接口，用户以插件形式接入。
由于这个框架起步阶段，有问题可以反馈给我，尽量解决。

**Comment by caoqianming** [comment]
好的😊，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月10日(周日) 下午5:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lizongying/go-crawler] 您好,想问一下跟colly相比的优势 (Issue #23)




 
可以用这个。
 golang比较好部署，直接可执行文件应该更适合第三方交付，可以保护你的代码。
 框架本身支持定时任务及自定义存储，方便。
 至于管理后台，这个主要还是针对爬虫的管理。至于数据管理考虑到数据的规模及结构千差万别，不适合做成通用的，后面可能会考虑提供接口，用户以插件形式接入。
 由于这个框架起步阶段，有问题可以反馈给我，尽量解决。
