### ISSUE TITLE
如何保存图片到本地目录

### ISSUE THREAD

**Issue by yy178** [lizongying/go-crawler#3]
能写个简单例子说明一下图片保存是怎么操作的吗

**Comment by lizongying** [comment]
> 能写个简单例子说明一下图片保存是怎么操作的吗

更新到最新版本。
参考 https://github.com/lizongying/go-crawler/tree/main/cmd/testFileSpider

**Comment by yy178** [comment]
参考了，还是不知道怎么保存图片到本地，可能我比较笨啊，望理解。比如网上图片https://www.baidu.com/img/pcyayunhuikaimushidoodle_35c0ef27c30a077f2e46ddb5db1993ef.gif,我想保存它在自定义目录并重新命名 d:/abc/123.gif
