### ISSUE TITLE
参考了，还是不知道怎么保存图片到本地

### ISSUE THREAD

**Issue by yy178** [lizongying/go-crawler#4]
参考了，还是不知道怎么保存图片到本地，可能我比较笨啊，望理解。比如网上图片https://www.baidu.com/img/pcyayunhuikaimushidoodle_35c0ef27c30a077f2e46ddb5db1993ef.gif,我想保存它在自定义目录并重新命名 d:/abc/123.gif，多个图片又如何保存，现在看明白了SetImagesRequest的切片设置，但SetImages这个是设置保存图片的吧，这个不知道要怎么设置才能保存到图片。

_Originally posted by @yy178 in https://github.com/lizongying/go-crawler/issues/3#issuecomment-1751907235_

**Comment by lizongying** [comment]
> ```
>           参考了，还是不知道怎么保存图片到本地，可能我比较笨啊，望理解。比如网上图片https://www.baidu.com/img/pcyayunhuikaimushidoodle_35c0ef27c30a077f2e46ddb5db1993ef.gif,我想保存它在自定义目录并重新命名 d:/abc/123.gif，多个图片又如何保存，现在看明白了SetImagesRequest的切片设置，但SetImages这个是设置保存图片的吧，这个不知道要怎么设置才能保存到图片。
> ```
> 
> _Originally posted by @yy178 in [#3 (comment)](https://github.com/lizongying/go-crawler/issues/3#issuecomment-1751907235)_

对不起，是我的失误。原例子里我不小心删除了`SetData(&DataImage{})`，没有Images字段可供保存图片的下载结果。

Item.data字段需要实现pkg.Image的切片，用于保存下载图片的结果。
      该字段的名称必须是Images，如`type DataImage struct {Images []*media.Image}`。

      `SetData(&DataImage{})`

请参考https://github.com/lizongying/go-crawler-example/blob/main/cmd/baiduImageSpider/

<img width="1413" alt="image" src="https://github.com/lizongying/go-crawler/assets/16871545/cc4c483c-ebf6-431d-90fd-ecd74cf1ba21">

<img width="1159" alt="image" src="https://github.com/lizongying/go-crawler/assets/16871545/6fc2539f-8abb-4a96-9276-79c11063ecdd">
